### ISSUE TITLE
Update for CodeHelp

### ISSUE THREAD

**Issue by DamianSuess** [dzzie/addins#1]
As a user it would be nice to have the latest version of CodeHelp add-in within the project. As of today 2.2 is the latest.

Reference:
http://www.planetsourcecode.com/vb/scripts/ShowCode.asp?txtCodeId=62468&lngWId=1

love the project, thank you!!

**Comment by dzzie** [comment]
Hi Damian, cant quite tell if the one I have archived in /Tabs/CodeHelp is the same project as this one or not but I will archive a copy of that code help as well. Trying to keep copies of useful VB6 code on hand so they dont get lost to time as various sites fall. Thanks for the link
