### ISSUE TITLE
ThunderVB startup crash 64bit

### ISSUE THREAD

**Issue by Assembly87** [dzzie/addins#4]
![image](https://user-images.githubusercontent.com/49219670/114641960-0277b780-9ca1-11eb-9ba2-87f4e0d3292f.png)

Windows 10 Pro 64Bit
Visual base 6.0 Enterprise with SP6 installed
Tried version 1.0.2. Same issue.

Further info
Crash seems to be coming from this function modHook::Deref called by modHook::HookDLLImport function. Particularly **RtlMoveMemory** API trying to read from a non-existent address.

**Comment by Assembly87** [comment]
The offending DLL is **ThunderVB_pl_HookSys_v1_0**.
It seems that there is an assumption of code section always reside in Imagebase + 0x1000. While it may seem right, in my Windows at least, Kernel32.dll's code section breaks this. 

![image](https://user-images.githubusercontent.com/49219670/114652697-6a83c900-9cb4-11eb-8d7e-4412f061ab16.png)

Take a look at where the code section of Kernel32.dll is. There is a gap of unallocated space. That's what causes the crash.
It seems this piece of code is badly coded. Looking for 'MZ' and 'PE' signatures of each loaded module with a Do While loop. Much better if you just read the values directly from the PE header to obtain the address of IAT.

**Comment by dzzie** [comment]
Hi thanks for the leg work on this. This addin isnt one of mine i am afraid, I just mirrored it so it would not be lost to the ages. I actually did run into this same problem in one of my other projects though. Should be an easy fix as you mentioned.

If i remember correctly ThunderVB allowed you to do "inline asm" in vb6? I have looked into these techniques over the years and personally just given up on wanting to use them. They are neat to explore and understand and pull off but in teh end of the day they make it hard to maintain and compile your code. I consider it beautiful that I can open a project file from 1998 and it still compiles fine without complex instructions.

My goto techniques are 
  1) the leader by far is just writing a small C dll for things vb cant do. drop it from a resource if you really want single file distribution
  2) "inline asm" through byte buffers and CallWindowProc trick. 
  3) replacing dummy vb module functions with a precompiled C obj file at linking. The best way to do this is by replacing link.exe with your own version, check out the version in this repo by jim white. Now were back into fragile compilation though so I never actually use this even though it can work without being horrible.

In terms of AV friendliness, VB6 exes already suffer from horrible false positives. So any extra trickery we do will probably get us flagged all the faster (like dropping a dll from resources or using the CallWindowProc trick for asm buffers)

If you keep tinkering with ThunderVB and get it back into shape feel free to submit a pull request or create a fork which I can link to. I agree its good to keep these resources operable so people can explore and advance VB6. All of my spare time has been flowing into runtime internals and pcode debugging / disassembly ( http://sandsprite.com/vbdec/ )

**Comment by dzzie** [comment]
also i do have a tested vb friendly hooklib which might be a easy replacement: https://github.com/dzzie/libs/tree/master/hooklib
and a PE parsing class if needed: https://github.com/dzzie/libs/tree/master/pe_lib

**Comment by Assembly87** [comment]
Hi dzzie,

Thanks for the reply. I didn't know you are not the coder of this plugin. Yes, the plugin allows you to inline ASM in VB6. It seems the project is pretty dead and there is no coder support for a long time. I have fixed the issue already but the pull request option is disabled. Probably because they come in a zipped format. So i have left the fixed project in the attachment. Maybe then you can attach it somehow to the main source code because it depends on some of modules there. I have tested it and it works fine under my Windows 10 64bit.

I agree with you. There are always other ways to achieve something. However, i have liked this plugin due to the ease of use and haven't found anything closer to it in terms of ASM friendliness. I had used it on my old 32bit system where it worked fine. The only downside is that you must have the project saved before you can compile. I haven't touched Visual basic for years. I had used the trick of CallWindowProc and EnumFonts hacks to call assembly code. Until Antiviruses started tagging them . Still i have some projects that i have to maintain from time to time but i don't feel like re coding them from scratch in another language just to fix or add few things.
Btw, nice project you got there. Good luck with it. Feel free to close this issue.


[ThunderVB_pl_HookSys_Win 10 64bit fix.zip](https://github.com/dzzie/addins/files/6312921/ThunderVB_pl_HookSys_Win.10.64bit.fix.zip)

**Comment by dzzie** [comment]
Awesome thanks for the update, I will add a link to this in the repo readme

**Comment by ercolesptr** [comment]
I came across ThunderVB lately and being still one of those stubborn VB6 coders was very interested to know that one can use C code and ASM directly in a VB6 project. So I went on and installed the plugin. After it gave me that 64-bit violation error mentioned above I have used the code in this thread to repair the DLL and is now working fine in my VB6 IDE. However it is not compiling the ASM or C code in the projects I tried from the examples. It is treating them simply as if they were empty lines. Can someone of you please help?

**Comment by dzzie** [comment]
Ive never used it im afraid. It probably requires some external compiler or assembler (nasm.exe?) to be where it can find it? 

Someone would have to scan through the source and see how it did its magic.
